### ISSUE TITLE
adding recipes

### ISSUE THREAD

**Issue by Moglibogli** [Platymemo/the-big-bench-theory#1]
does this allow for nbt crafting? like with [Nbt Crafting (Fabric)](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting)

**Comment by Platymemo** [comment]
It has full compatibility with [Nbt Crafting (Fabric)](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting), but no innate nbt crafting support on its own. You will need to have nbt crafting installed as well.
