### ISSUE TITLE
rei compat? server crash on startup

### ISSUE THREAD

**Issue by superon** [Platymemo/the-big-bench-theory#5]
currently experiencing this on the server (dedicated) on startup.
https://pastebin.com/Jiu5TGLP
the client runs fine

fabric-api-0.42.0+1.16
big-bench-theory-1.0.2
RoughlyEnoughItems-5.12.248

**Comment by Platymemo** [comment]
It's due to the `MegaCraftingContainerPlugin` calling a field in `MegaCraftingPlugin`, which is client-only, my bad. I will release a new version on CF and Modrinth to fix this, but that will be my last 1.16 update
